# Generated by Django 3.1.6 on 2021-02-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsbot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Info',
        ),
    ]
